### ISSUE TITLE
breaking tst/opers/StructureDescription.tst in GAP

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/groupoids#7]
I'm afraid this problem in `testinstall` in GAP's master branch is caused by Groupoids 1.52
```
########> Diff in /Volumes/hudson-fs/workspace/GAP-master-test/GAPCOPTS/64buil\
d/GAPTARGET/standard/label/fruitloop/GAP-master-snapshot/tst/testinstall/opers\
/StructureDescription.tst:108
# Input is:
StructureDescription(G);
# Expected output:
"C0 x C0"
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
The 1st argument is 'fail' which might point to an earlier problem
Error, no 1st choice method found for `Range' on 1 arguments
########
```

**Comment by cdwensley** [comment]
How do I find out how this is caused by groupoids? 

ChristoleysiMac:groupoids christopherwensley$ ../../dev.sh 
 ┌───────┐   GAP 4.8.7-4133-gdf02079-dirty of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin16.7.0-gcc-default64
 Configuration:  gmp 6.0.0
 Loading the library and packages ...
LoadPackage("groupoids Components: trans 1.0, prim 3.0, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.0, AutPGrp 1.6, 
             CRISP 1.4.3, Cryst 4.1.12, CrystCat 1.1.6, CTblLib 1.2.2, 
             FactInt 1.5.3, FGA 1.3.1, GAPDoc 1.5.1, IRREDSOL 1.2.4, 
             LAGUNA 3.7.0, Polenta 1.3.6, Polycyclic 2.11, RadiRoot 2.7, 
             ResClasses 4.4.2, Sophus 1.23, SpinSym 1.5, TomLib 1.2.5, 
             utils 0.48
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> LoadPackage("groupoids");
#I  Semigroups: the kernel module is not compiled, the package cannot be loaded.
Loading groupoids 1.53 (algorithms for finite groupoids)
by Emma Moore and Chris Wensley (http://pages.bangor.ac.uk/~mas023/)
--------------------------------------------------------------------
true
gap> F := FreeGroup("r", "s");; r := F.1;; s := F.2;;
gap> G := F/[s^2, r^3, s*r*s*r];;
gap> StructureDescription(G);
"S3"
gap> G := F/[s*r*s^(-1)*r^(-1)];;
gap> StructureDescription(G);    
"C0 x C0"

**Comment by alex-konovalov** [comment]
@cdwensley can you try in the GAP master branch?

**Comment by alex-konovalov** [comment]
Ok, passes in the master branch, sorry!
```
gap> LoadPackage("group":OnlyNeeded);
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  FGA 1.3.1 (Free Group Algorithms)
by Christian Sievers (c.sievers@tu-bs.de).
Homepage: http://www.icm.tu-bs.de/ag_algebra/software/FGA/
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Loading groupoids 1.52 (algorithms for finite groupoids)
by Emma Moore and Chris Wensley (http://pages.bangor.ac.uk/~mas023/)
--------------------------------------------------------------------
true
gap> Test("tst/testinstall/opers/StructureDescription.tst");
StructureDescription.tst            
msecs: 3230
true
```

**Comment by alex-konovalov** [comment]
I think it's Semigroups instead: https://github.com/gap-packages/Semigroups/issues/393
